apiVersion: v2
appVersion: "1.2"
description: A Helm chart for Synapse monitoring, which including prometheus-operator, synapse-prometheus-connector
name: synapse-prometheus-operator
version: 0.1.2
maintainers:
  - name: kaizho
    email: kaizho@microsoft.com
  - name: zhwe
    email: zhwe@microsoft.com
dependencies:
  - name: kube-prometheus-stack
    version: 36.2.*
    repository: https://prometheus-community.github.io/helm-charts
    import-values:
    - child: grafana
      parent: grafana
