{
 "title": "Synapse Workspace / Workspace",
 "tags": [
  "Synapse",
  "Spark"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "WORKSPACE",
    "label": "Workspace",
    "query": "label_values(synapse_connector_spark_pool_info, workspace_name)"
   },
   {
    "name": "subscription_id",
    "query": "label_values(synapse_connector_application_info{workspace_name=\"$WORKSPACE\"}, subscription_id)"
   },
   {
    "name": "resource_group",
    "query": "label_values(synapse_connector_application_info{workspace_name=\"$WORKSPACE\"}, resource_group)"
   }
  ]
 },
 "panels": [
  { "title": "Header", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Application Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(synapse_connector_application_info{workspace_name=\"$WORKSPACE\"}) by (application_id)",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Current Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_memoryUsed_bytes{workspace_name=\"$WORKSPACE\"})"
    }
   ]
  },
  {
   "title": "Current Total Cores",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(spark_executor_totalCores{workspace_name=\"$WORKSPACE\"}))",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  { "title": "Spark Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Active Spark pools",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nmax_over_time(\n   max(synapse_connector_application_info{workspace_name=\"$WORKSPACE\"}) by (workspace_name, spark_pool_name)\n   [$__range:2m]\r)\n   ,\"info\", \"Manage\", \"\", \"\")"
    },
    {
     "expr": "count(\n  max(spark_executor_totalDuration_seconds_total{workspace_name=\"$WORKSPACE\"}) by (spark_pool_name, application_id)\n) by (spark_pool_name)"
    }
   ]
  },
  {
   "title": "Total Running CPU Cores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_executor_totalCores{workspace_name=\"$WORKSPACE\"}) by (workspace_name)",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Spark Pools",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "synapse_connector_spark_pool_info{workspace_name=\"$WORKSPACE\"}"
    }
   ]
  }
 ]
}