{
 "title": "Synapse Workspace / Spark Application",
 "tags": [
  "Synapse",
  "Spark"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "workspace_name",
    "label": "Workspace",
    "query": "label_values(spark_executor_totalDuration_seconds_total{}, workspace_name)"
   },
   {
    "name": "spark_pool_name",
    "label": "Spark pool",
    "query": "label_values(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\"}, spark_pool_name)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}, name)"
   },
   {
    "name": "application_name",
    "label": "Application Name",
    "query": "label_values(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", name=\"$name\"}, application_name)"
   },
   {
    "name": "application_id",
    "label": "Application ID",
    "query": "label_values(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", name=\"$name\"}, application_id)"
   },
   {
    "name": "resource_group",
    "query": "label_values(synapse_connector_application_info{workspace_name=\"$workspace_name\"}, resource_group)"
   },
   {
    "name": "subscription_id",
    "query": "label_values(synapse_connector_application_info{workspace_name=\"$workspace_name\"}, subscription_id)"
   },
   {
    "name": "livy_id",
    "query": "label_values(synapse_connector_application_info{workspace_name=\"$workspace_name\", application_id=\"$application_id\"}, livy_id)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Executors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count(spark_executor_memoryUsed_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\", application_id=\"$application_id\"})\n  by (spark_pool_name, executor_id, application_id, name, application_name))\nby (spark_pool_name, application_id, name, application_name)",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Storage Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_memoryUsed_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\", application_id=\"$application_id\"}) by (application_id)\n/\nsum(spark_executor_maxMemory_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\", application_id=\"$application_id\"}) by (application_id)"
    }
   ]
  },
  {
   "title": "Driver Storage Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spark_executor_memoryUsed_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id=\"driver\"}) by (application_id)\n/ \nmax(spark_executor_maxMemory_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id=\"driver\"}) by (application_id)"
    }
   ]
  },
  {
   "title": "Max Executor GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(spark_executor_totalGCTime_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_totalGCTime_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Max Tasks on Executor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(spark_executor_activeTasks{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_failedTasks_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\"})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_completedTasks_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\", application_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "synapse_connector_application_queue_duration{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}"
    },
    {
     "expr": "max(synapse_connector_application_submit_time{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}) by (application_id) * 1000"
    },
    {
     "expr": "max(synapse_connector_application_running_duration{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}) by (application_id)"
    }
   ]
  },
  { "title": "Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Application Executors Current Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  max(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"})\n  by (spark_pool_name, application_id, name, application_name, executor_id)[$__range:2m]\r\n)"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Tasks Time per Executor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_executor_memoryUsed_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}",
     "legendFormat": "[{{name}}] executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Duration / Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\", executor_id!=\"driver\"}[2m])) \nby (name, application_name)",
     "legendFormat": "[{{name}}]"
    }
   ]
  },
  {
   "title": "Executor GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_totalGCTime_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}[1m])",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Active Tasks per Executor",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_executor_activeTasks{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_totalShuffleRead_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_totalShuffleWrite_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Input Bytes/Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_totalInputBytes_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Shuffle IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spark_executor_totalShuffleWrite_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(spark_executor_totalShuffleRead_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}