{
 "title": "Synapse Workspace / Sparkpools",
 "tags": [
  "Synapse",
  "Spark"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "workspace_name",
    "label": "Workspace",
    "query": "label_values(spark_executor_totalDuration_seconds_total{}, workspace_name)"
   },
   {
    "name": "spark_pool_name",
    "label": "Spark pool",
    "query": "label_values(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\"}, spark_pool_name)"
   },
   {
    "name": "resource_group",
    "query": "label_values(synapse_connector_application_info{workspace_name=\"$workspace_name\"}, resource_group)"
   },
   {
    "name": "subscription_id",
    "query": "label_values(synapse_connector_application_info{workspace_name=\"$workspace_name\"}, subscription_id)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Executors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  sum(spark_executor_memoryUsed_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\"})\n  by (spark_pool_name, executor_id, application_id, name, application_name))\nby (spark_pool_name, application_id, name, application_name)",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_memoryUsed_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\"}) by (workspace_name, spark_pool_name)\n/\nsum(spark_executor_maxMemory_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\"}) by (workspace_name, spark_pool_name)"
    }
   ]
  },
  {
   "title": "Driver Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spark_executor_memoryUsed_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id=\"driver\"}) by (workspace_name, spark_pool_name)\n/ \nmax(spark_executor_maxMemory_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id=\"driver\"}) by (workspace_name, spark_pool_name)"
    }
   ]
  },
  {
   "title": "Max Executor GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(spark_executor_totalGCTime_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}[1m]))"
    }
   ]
  },
  {
   "title": "Max Tasks on Executor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(spark_executor_activeTasks{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_failedTasks_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\"})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_completedTasks_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\"})"
    }
   ]
  },
  { "title": "Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Applications Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  max(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"})\n  by (workspace_name, spark_pool_name, application_id, name, application_name)[$__range:2m]\r\n)"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Duration / Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(spark_executor_totalDuration_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", executor_id!=\"driver\"}[2m])) \nby (workspace_name, spark_pool_name, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Executor Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (\n  spark_executor_memoryUsed_bytes{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}\n) by (workspace_name, spark_pool_name, name, application_name, application_id)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Tasks per Executor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_executor_activeTasks{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}) by (worksapce_name, spark_pool_name, name, application_name, application_id)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Executor GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(spark_executor_totalGCTime_seconds_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}[1m])\n) by (workspace_name, spark_pool_name, name, application_name, application_id)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spark_executor_totalShuffleRead_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}[5m]))\nby (workspace_name, spark_pool_name, name, application_name, application_id)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(spark_executor_totalShuffleWrite_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}[5m])\n) by (workspace_name, spark_pool_name, name, application_name, application_id)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Input Bytes/Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (\r\n  rate(spark_executor_totalInputBytes_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}[5m])\n) by (workspace_name, spark_pool_name, name, application_name, application_id)\r",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Shuffle IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(spark_executor_totalShuffleWrite_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}[5m]))\nby (workspace_name, spark_pool_name, name, application_name, application_id)",
     "legendFormat": "{{name}} Write"
    },
    {
     "expr": "sum(\n  rate(spark_executor_totalShuffleRead_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\"}[5m]))\nby (workspace_name, spark_pool_name, name, application_name, application_id)",
     "legendFormat": "{{name}} Read"
    }
   ]
  }
 ]
}